security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 4
            time_cost: 3
            memory_cost: 10
    providers:
        # users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: logout
            form_login:
                login_path: login
                check_path: login
                enable_csrf: false
                default_target_path: admin.blog.index
            login_throttling:
                max_attempts: 3
            switch_user: true
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/dashboard, roles: ROLE_USER }
