<?php

namespace Container0cMU8r9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KYwJL_EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KYwJL.e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KYwJL.e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminBlogController::delete' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\Admin\\AdminBlogController::edit' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AdminBlogController:delete' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\Admin\\AdminBlogController:edit' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AdminBlogController::delete' => '?',
            'App\\Controller\\Admin\\AdminBlogController::edit' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AdminBlogController:delete' => '?',
            'App\\Controller\\Admin\\AdminBlogController:edit' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
